# Generated by Django 3.2.12 on 2022-10-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=4)),
                ('mass', models.CharField(max_length=4)),
                ('gender', models.CharField(max_length=8)),
                ('homeworld', models.CharField(max_length=50)),
            ],
        ),
    ]
